[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "ikeda-any"
build_on_update = true

[mode.repository.signing]
enabled = false

[repositories]
repos = [
	"pkg:filesystem",
	"pkg:base",
]

[repositories.urls]
ikd = "https://github.com/ikeda-linux/%repo%"
pkg = "https://github.com/ikeda-linux/pkgbuild.%repo%"
