mode = "repository"
name = "ikeda-x86_64"
repo = [
	"2::rustysd",
	"2::zsh",
	"2::ncurses",
	"2::linux-vm",
	"2::linux-vanilla",
	"2::linux-firmware",
	"2::busybox",
	"2::bash",
]
urls = [
	"https://github.com/ikeda-linux/%repo%",
	"https://github.com/ikeda-linux/pkgbuild.%repo%"
]
