[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "ikeda-x86_64"
build_on_update = true

[mode.repository.signing]
enabled = false

[repositories]
repos = [
	"pkg:rustysd",
	"pkg:zsh",
	"pkg:ncurses",
	"pkg:linux-vm",
	"pkg:linux-vanilla",
	"pkg:linux-firmware",
	"pkg:busybox",
	"pkg:bash",
	"pkg:pacman",
	"pkg:runit",
	"pkg:limine",
	"pkg:musl",
]

[repositories.urls]
ikd = "https://github.com/ikeda-linux/{}"
pkg = "https://github.com/ikeda-linux/pkgbuild.{}"
