[base]
mode = "workspace"
smart_pull = true

[mode.workspace]
git_info = true
colorblind = false

[repositories]
repos = [
	"pkg:rustysd",
	"pkg:zsh",
	"pkg:ncurses",
	"pkg:linux-vm",
	"pkg:linux-firmware",
	"pkg:busybox",
	"pkg:bash",
	"pkg:pacman",
	"pkg:filesystem",
	"pkg:base",
	"pkg:runit",
	"pkg:limine",
	"ikd:image",
	"pkg:musl",
	"pkg:gcc",
	"pkg:chibicc",
	"pkg:openssl",
	"pkg:wpa_supplicant",
	"pkg:e2fsprogs",
	"pkg:mkikeda",
	"pkg:ca-certificates",
	"pkg:nss",
	"ikd:package",
	"pkg:p11-kit",
	"pkg:micro",
	"pkg:libidn",
	"pkg:lynx",
]

[repositories.urls]
ikd = "ssh://git@github.com/ikeda-linux/{}"
pkg = "ssh://git@github.com/ikeda-linux/pkgbuild.{}"
