mode = "workspace"

repo = [
	"2::rustysd",
	"2::zsh",
	"2::ncurses",
	"2::linux-vm",
	"2::linux-vanilla",
	"2::linux-firmware",
	"2::busybox",
	"2::bash",
	"2::pacman",
	"2::filesystem",
	"2::base",
	"2::runit",
]

urls = [
	"ssh://git@github.com/ikeda-linux/%repo%",
	"ssh://git@github.com/ikeda-linux/pkgbuild.%repo%"
]
